apiVersion: v1
kind: Service
metadata:
  name: ${pod_name}
  labels:
    app: ${antidote_datacenter}
    type: pod-service
spec:
  type: LoadBalancer
  ports:
  - port: 8087
    name: antidote-pb
  selector:
    app: ${antidote_datacenter}
    statefulset.kubernetes.io/pod-name: ${pod_name}
