apiVersion: v1
kind: Service
metadata:
  name: ${antidote_datacenter}
  labels:
    app: ${antidote_datacenter}
    type: ${antidote_datacenter}-headless
spec:
  clusterIP: None
  selector:
    app: ${antidote_datacenter}
    type: instance