apiVersion: v1
kind: Service
metadata:
  name: dc1-0
  labels:
    app: dc1
    type: pod-service
spec:
  type: LoadBalancer
  ports:
  - port: 8087
    name: antidote-pb
  selector:
    app: dc1
    statefulset.kubernetes.io/pod-name: dc1-0
