apiVersion: batch/v1
kind: Job
metadata:
  name: connector-for-dc1-dc2
  labels:
    type: antidote-util-tmp
spec:
  ttlSecondsAfterFinished: 5
  template:
    spec:
      containers:
      - name: antidote-connect
        image: peterzel/antidote-connect
        imagePullPolicy: Always
        args: ["--connectDcs", "172.18.0.4:8087","172.18.0.10:8087"] ## first_node with format hostname:port and list of antidote nodes format antidote@hostname
      restartPolicy: Never
  backoffLimit: 4